### ISSUE TITLE
Timeframe

### ISSUE THREAD

**Issue by nikoloskif** [jptsantossilva/Trading-BOT-EMA-cross-Binance-API#1]
Hi. Great script. Concise and logical code. But, please tell me why the code does not run on timelines of 1 hour, 4 hours, 1 day?

**Comment by jptsantossilva** [comment]
Hi @nikoloskif ,
This was my first approach. Take a look at my other repository https://github.com/jptsantosilva/Binance-Trading-bot-EMA-Cross. That is an evolution of this one and works on the time frames you mentioned.

I'm going to delist this repository since there is no reason to keep it.
